console.log(document);
const link = document.querySelector('#image');
link.textContent = 'this is a dynamically modified DOM text content';
link.href = 'https://en.wikipedia.org/wiki/Cat';
const img = document.getElementById('image');
// console.log(img);
const paragraphs = document.getElementsByClassName('paragraph');
// console.log(paragraphs[0]);
const section = document.querySelector('section');
const newParagraph = document.createElement('p');
section.appendChild(newParagraph);
// const text = document.createTextNode('This is another paragraph.');
// newParagraph.appendChild(text);
newParagraph.innerHTML = 'This is another <a href="https://en.wikipedia.org/wiki/Cat">paragraph</a>.';
newParagraph.style.color = 'pink';
newParagraph.style.backgroundColor = 'black';
newParagraph.style.padding = '10px';
// section.removeChild(newParagraph);
// console.log(newParagraph);
